async function team(tab='members'){const allowed=canManageTeam(); head('Team Members','Invite users, change roles, disable access, force MFA and restrict project access.',allowed?'<button class="btn primary" onclick="openTeamForm()">Invite Member</button>':''); const rows=tab==='members'?await api('/api/customer/team'):[]; $('#content').innerHTML=`<div class="panel"><div class="tabs"><button class="tab ${tab==='members'?'active':''}" onclick="team('members')" type="button">Members</button><button class="tab ${tab==='permissions'?'active':''}" onclick="team('permissions')" type="button">Permissions</button></div>${tab==='permissions'?teamPermissions():table(['Name','Email','Role','MFA','Projects','Status','Actions'],rows.map(u=>[esc(u.name),esc(u.email),esc(u.role),u.mfa_required?'Required':'No',esc((u.project_access||[]).join(', ')||'All'),u.is_active?badge('active'):badge('disabled'),allowed?`<button class="btn sm" onclick='openTeamForm(${JSON.stringify(u).replaceAll("'","&#039;")})'>Edit</button>`:'<span class="small muted">Read only</span>']))}</div>`}
function teamPermissions(){return `${table(['Role','API Keys','Projects','Billing','Team','Webhooks','Reports / Usage'],[
  ['owner','Create, edit, rotate, revoke','Create, edit, disable','Buy credits, cards, auto-recharge','Invite and edit members','Create, edit, test','View'],
  ['admin','Create, edit, rotate, revoke','Create, edit, disable','Buy credits, cards, auto-recharge','Invite and edit members','Create, edit, test','View'],
  ['developer','Create, edit, rotate, revoke','Create and edit','Read only','Read only','Create, edit, test','View'],
  ['billing_manager','Read only','Read only','Buy credits, cards, auto-recharge','Read only','Read only','View'],
  ['viewer','Read only','Read only','Read only','Read only','Read only','View']
].map(r=>[badge(r[0]),...r.slice(1).map(esc)]))}<p class="small muted">Permissions shown here match the customer portal backend authorization rules. Suspended or non-active customer accounts can still be blocked from creating or reactivating API keys.</p>`}
async function openTeamForm(u=null){if(!canManageTeam())return denyReadonly('Only owner and admin roles can manage team members.'); const projects=await api('/api/customer/projects'); const selected=u?.project_access||[]; $('#modal').className='modal'; $('#modal').innerHTML=`<div class="modal-card"><div class="panel-head"><h2>${u?'Edit':'Invite'} Member</h2><button class="btn" onclick="closeModal()">Close</button></div><div class="form-grid"><label>Name<input id="tm_name" value="${esc(u?.name||'')}"></label><label>Email<input id="tm_email" value="${esc(u?.email||'')}"></label><label>Role<select id="tm_role"><option>owner</option><option>admin</option><option>developer</option><option>billing_manager</option><option>viewer</option></select></label><label>Status<select id="tm_active"><option value="true" ${u?.is_active!==false?'selected':''}>active</option><option value="false" ${u?.is_active===false?'selected':''}>disabled</option></select></label><label>MFA<select id="tm_mfa"><option value="false" ${!u?.mfa_required?'selected':''}>not required</option><option value="true" ${u?.mfa_required?'selected':''}>required</option></select></label><label>Project access<select id="tm_projects" multiple size="5">${projects.map(p=>`<option value="${p.id}" ${selected.includes(p.id)?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><button class="btn primary" onclick="saveTeam(${u?.id||0})">Save Member</button><p class="small muted">New invited user default password: password123</p></div></div>`; if(u) tm_role.value=u.role;}
async function saveTeam(id){if(!canManageTeam())return denyReadonly('Only owner and admin roles can manage team members.'); const payload={role:tm_role.value,is_active:tm_active.value==='true',mfa_required:tm_mfa.value==='true',project_access:[...tm_projects.selectedOptions].map(o=>Number(o.value))}; if(!id){payload.name=tm_name.value;payload.email=tm_email.value;} await api(id?`/api/customer/team/${id}`:'/api/customer/team',{method:id?'PUT':'POST',body:JSON.stringify(payload)}); closeModal(); await team()}
