async function team(tab='members'){const allowed=canManageTeam(); head('Team Members','Invite users, change roles, disable access, force MFA and review role permissions.',allowed?'<button class="btn primary" onclick="openTeamForm()">Invite Member</button>':''); const rows=tab==='members'?await api('/api/customer/team'):[]; $('#content').innerHTML=`<div class="panel"><div class="tabs"><button class="tab ${tab==='members'?'active':''}" onclick="team('members')" type="button">Members</button><button class="tab ${tab==='permissions'?'active':''}" onclick="team('permissions')" type="button">Permissions</button></div>${tab==='permissions'?teamPermissions():table(['Name','Email','Role','MFA','Status','Actions'],rows.map(u=>[esc(u.name),esc(u.email),esc(u.role),u.mfa_required?'Required':'No',u.is_active?badge('active'):badge('disabled'),allowed?`<button class="btn sm" onclick='openTeamForm(${JSON.stringify(u).replaceAll("'","&#039;")})'>Edit</button>`:'<span class="small muted">Read only</span>']))}</div>`}
function teamPermissions(){return `${table(['Role','API Keys','Billing','Team','Webhooks','Reports / Usage'],[
  ['owner','Create, edit, rotate, revoke','Buy credits, cards, auto-recharge','Invite and edit members','Create, edit, test','View'],
  ['admin','Create, edit, rotate, revoke','Buy credits, cards, auto-recharge','Invite and edit members','Create, edit, test','View'],
  ['developer','Create, edit, rotate, revoke','Read only','Read only','Create, edit, test','View'],
  ['billing_manager','Read only','Buy credits, cards, auto-recharge','Read only','Read only','View'],
  ['viewer','Read only','Read only','Read only','Read only','View']
].map(r=>[badge(r[0]),...r.slice(1).map(esc)]))}<p class="small muted">Permissions shown here match the customer portal backend authorization rules. Suspended or non-active customer accounts can still be blocked from creating or reactivating API keys.</p>`}
async function openTeamForm(u=null){if(!canManageTeam())return denyReadonly('Only owner and admin roles can manage team members.'); $('#modal').className='modal'; $('#modal').innerHTML=`<div class="modal-card user-form-modal"><div class="modal-titlebar"><div><div class="eyebrow">Team access</div><h2>${u?'Edit team member':'Invite team member'}</h2><p>${u?'Update this member role, status, and security requirements.':'Add a customer portal user and assign the right access role.'}</p></div><button class="btn" onclick="closeModal()">Close</button></div><div class="user-form-card"><div id="teamFormError" class="portal-alert warning form-error" role="alert"></div><div class="user-form-section"><div class="section-title"><h3>Member</h3><p>Use a work email address. New members receive the default temporary password from the current backend flow.</p></div><div class="form-grid two-col"><label class="form-field">Name<input id="tm_name" value="${esc(u?.name||'')}" ${u?'disabled':''}></label><label class="form-field">Email<input id="tm_email" type="email" value="${esc(u?.email||'')}" ${u?'disabled':''}></label></div></div><div class="user-form-section"><div class="section-title"><h3>Access</h3><p>Choose the role and whether the user can currently access the portal.</p></div><div class="form-grid two-col"><label class="form-field">Role<select id="tm_role"><option value="owner">Owner</option><option value="admin">Admin</option><option value="developer">Developer</option><option value="billing_manager">Billing manager</option><option value="viewer">Viewer</option></select></label><label class="form-field">Status<select id="tm_active"><option value="true" ${u?.is_active!==false?'selected':''}>Active</option><option value="false" ${u?.is_active===false?'selected':''}>Disabled</option></select></label><label class="form-field">MFA requirement<select id="tm_mfa"><option value="false" ${!u?.mfa_required?'selected':''}>Not required</option><option value="true" ${u?.mfa_required?'selected':''}>Required</option></select></label></div></div>${u?'':'<div class="portal-alert information" style="display:flex;margin:0">New invited users are created with temporary password <span class="mono">password123</span>. Ask them to change it from Account Settings after first sign-in.</div>'}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveTeam(${u?.id||0})">${u?'Save Changes':'Send Invite'}</button></div></div>`; if(u) tm_role.value=u.role;}
async function saveTeam(id){if(!canManageTeam())return denyReadonly('Only owner and admin roles can manage team members.'); if(!id&&!tm_name.value.trim())return setFormError('Member name is required.',tm_name,'teamFormError'); if(!id&&(!tm_email.value.trim()||!tm_email.value.includes('@')))return setFormError('Enter a valid work email address.',tm_email,'teamFormError'); const payload={role:tm_role.value,is_active:tm_active.value==='true',mfa_required:tm_mfa.value==='true',project_access:[]}; if(!id){payload.name=tm_name.value.trim();payload.email=tm_email.value.trim();} await api(id?`/api/customer/team/${id}`:'/api/customer/team',{method:id?'PUT':'POST',body:JSON.stringify(payload),successMessage:id?'Team member access was updated.':'Team member invited with a temporary password.'}); closeModal(); await team()}
