const API_BASE = '';
let token = localStorage.getItem('pepiko_customer_token') || '';
let user = JSON.parse(localStorage.getItem('pepiko_customer_user') || 'null');
let currentPage = 'dashboard';
let selectedPlaygroundProductCode = '';
let productNavRefreshTimer = null;
let cache = {};
const pages = [
  ['dashboard','Overview','⌂'],['playground','API Playground','▣'],['apiKeys','API Keys','🔑'],['usage','Usage','◷'],['billing','Billing / Credits','◉'],['reports','Reports','▧'],['projects','Projects / Apps','▦'],['team','Team Members','◌'],['webhooks','Webhooks','⤴'],['audit','Audit Logs','≣'],['support','Help / Support','?']
];
const routeBase = '';
const pageRoutes = {dashboard:'dashboard',playground:'playground',apiKeys:'api-keys',usage:'usage',billing:'billing',reports:'reports',projects:'projects',team:'team',webhooks:'webhooks',audit:'audit',support:'support'};
const routePages = Object.fromEntries(Object.entries(pageRoutes).map(([page, route]) => [route, page]));
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const esc = s => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money = n => Number(n || 0).toLocaleString(undefined,{maximumFractionDigits:2});
const date = d => d ? new Date(d).toLocaleString() : '-';
const badge = v => `<span class="status ${esc(String(v||'').toLowerCase())}">${esc(v||'-')}</span>`;
const hasRole = (...roles) => roles.includes(user?.role);
const canManageApiKeys = () => hasRole('owner','admin','developer');
const canManageProjects = () => hasRole('owner','admin','developer');
const canDisableProjects = () => hasRole('owner','admin');
const canManageTeam = () => hasRole('owner','admin');
const canManageBilling = () => hasRole('owner','admin','billing_manager');
const canManageWebhooks = () => hasRole('owner','admin','developer');
const accountStatus = () => user?.organization_status || user?.organization?.status || 'active';
const accountBlocked = () => accountStatus() !== 'active';
const accountBlockedMessage = () => `Customer account is ${accountStatus()}. Access is currently disabled. Contact Pepiko support or your account owner to reactivate the account.`;
function brand(panel='Customer Portal'){return `<div class="login-brand"><div class="brand">pepiko<span class="brand-ai">.ai</span></div><div class="brand-panel">${panel}</div></div>`}
function table(headers, rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">No data yet</td></tr>`}</tbody></table>`}
function setStatus(msg='', kind='information'){const el=$('#status'); if(!el)return; const type=kind===true||kind==='error'?'error':kind==='success'?'success':kind==='warning'?'warning':'information'; el.textContent=msg; el.className=`portal-alert ${type}`; el.style.display=msg?'flex':'none'}
function setFormError(msg='',field=null,target='formError'){const el=typeof target==='string'?($(`#${target}`)||$(target)):target; $$('.field-invalid').forEach(x=>x.classList.remove('field-invalid')); if(!msg){if(el){el.textContent='';el.style.display='none'} return false} if(el){el.textContent=msg;el.className='portal-alert warning form-error';el.style.display='flex';el.scrollIntoView({block:'nearest'})}else setStatus(msg,'warning'); if(field){field.classList.add('field-invalid');field.focus?.()} return false}
function renderPageLoading(){const el=$('#content'); if(el)el.innerHTML='<div class="panel empty">Loading...</div>'}
function denyReadonly(message='Your current role can view this section but cannot make changes.'){setStatus(message,true)}
function successMessage(path, method){if(path.includes('/auth/login'))return 'Signed in successfully.'; if(path.includes('/auth/register'))return 'Account created successfully. Continue onboarding.'; if(path.includes('/onboarding/api-key'))return 'Onboarding API key created. Copy it now because it will only be shown once.'; if(path.includes('/onboarding/invite'))return 'Team invitations were sent successfully.'; if(path.includes('/api-keys/')&&path.endsWith('/rotate'))return 'API key rotated. Copy the new key now because it will only be shown once.'; if(path.includes('/api-keys/')&&path.endsWith('/revoke'))return 'API key revoked. It can no longer be used for API requests.'; if(path.includes('/api-keys'))return method==='DELETE'?'API key deleted permanently.':method==='POST'?'API key created. Copy the full key now because it will only be shown once.':'API key settings updated.'; if(path.includes('/projects/')&&path.endsWith('/disable'))return 'Project disabled. Related access should be reviewed before re-enabling.'; if(path.includes('/projects'))return method==='POST'?'Project created successfully.':'Project settings updated.'; if(path.includes('/billing/top-up'))return 'Credits added to the wallet successfully.'; if(path.includes('/billing/payment-methods'))return 'Payment method added successfully.'; if(path.includes('/billing/auto-recharge'))return 'Auto-recharge settings updated.'; if(path.includes('/team'))return method==='POST'?'Team member invited successfully.':'Team member access updated.'; if(path.includes('/webhooks/')&&path.endsWith('/test'))return 'Webhook test event sent. Check the delivery status below.'; if(path.includes('/webhooks'))return method==='POST'?'Webhook endpoint created successfully.':'Webhook endpoint updated.'; if(path.includes('/support/tickets/')&&path.includes('/comments'))return 'Reply added to the support ticket.'; if(path.includes('/support/tickets'))return 'Support ticket created successfully.'; const resource=path.split('?')[0].split('/').filter(Boolean).slice(-1)[0]||'request'; return `${method} ${resource.replaceAll('-',' ')} completed successfully.`}
async function api(path, opts={}){if(accountBlocked()&&!path.startsWith('/api/customer/auth/')){const err=new Error(accountBlockedMessage()); err.status=403; setStatus(err.message,'warning'); throw err;} const headers=opts.headers||{}; if(token)headers.Authorization=`Bearer ${token}`; if(opts.body && !headers['Content-Type'])headers['Content-Type']='application/json'; const method=(opts.method||'GET').toUpperCase(); const res=await fetch(API_BASE+path,{cache:'no-store',...opts,headers}); let data=null; try{data=await res.json()}catch{} if(!res.ok){const err=new Error((data&&data.detail)||res.statusText); err.status=res.status; setStatus(err.message,true); throw err;} if(method!=='GET')setStatus(opts.successMessage||successMessage(path,method),'success'); return data;}
function routeForPage(id, productCode=''){return id==='playground'&&productCode?`/playground/${encodeURIComponent(productCode)}`:`/${pageRoutes[id]||pageRoutes.dashboard}`}
function pageFromPath(path=location.pathname){const clean=path.replace(/\/+$/,''); if(clean==='')return 'dashboard'; const route=clean.replace(/^\/+/,'').split('/')[0]; return routePages[route]||'dashboard'}
function productFromPath(path=location.pathname){const clean=path.replace(/\/+$/,''); const prefix='/playground/'; return clean.startsWith(prefix)?decodeURIComponent(clean.slice(prefix.length)):''}
function pushRoute(id, productCode=''){const next=routeForPage(id, productCode); if(location.pathname!==next)history.pushState({page:id,productCode},'',next)}
function logout(){localStorage.removeItem('pepiko_customer_token');localStorage.removeItem('pepiko_customer_user');location.href='/'}
async function login(e){e.preventDefault(); setStatus('Signing in...'); try{const d=await api('/api/customer/auth/login',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})}); token=d.access_token; user={...d.user,organization_status:d.user?.organization_status||d.organization?.status||'active'}; localStorage.setItem('pepiko_customer_token',token); localStorage.setItem('pepiko_customer_user',JSON.stringify(user)); renderApp()}catch(err){setStatus(err.message,true)}}
function shell(){document.body.innerHTML=`<div class="portal"><aside class="sidebar"><div class="sidebar-head"><a class="brand" href="${routeForPage('dashboard')}" data-route="dashboard"><span>pepiko</span><span class="brand-ai">.ai</span></a></div><select class="org-select" aria-label="Organization"><option>${esc(user?.organization_name||'BrightMinds Inc.')}</option></select><nav>${pages.filter(p=>p[0]!=='support').map(p=>`<a class="nav-link ${accountBlocked()?'disabled':''}" href="${routeForPage(p[0])}" data-page="${p[0]}"><span class="nav-icon">${p[2]}</span>${p[1]}</a>${p[0]==='playground'&&!accountBlocked()?'<div id="playgroundProductNav" class="product-subnav"></div>':''}`).join('')}</nav><div class="side-bottom"><a class="nav-link ${accountBlocked()?'disabled':''}" href="${routeForPage('support')}" data-page="support"><span class="nav-icon">◔</span>Help & Support</a><button class="nav-link" onclick="logout()" type="button"><span class="nav-icon">⇥</span>Logout</button></div></aside><main class="main"><header class="topbar"><div class="search"><span>⌕</span><input placeholder="Search API keys, reports, docs, and logs..." aria-label="Search" ${accountBlocked()?'disabled':''}></div><select class="env" aria-label="Environment" ${accountBlocked()?'disabled':''}><option>Production</option><option>Staging</option><option>Development</option></select><div class="top-actions"><button class="bell" type="button" onclick="showPage('support')" aria-label="Notifications" ${accountBlocked()?'disabled':''}>♢</button><div class="user"><div class="avatar">${esc((user?.name||'AR').split(' ').map(x=>x[0]).join('').slice(0,2))}</div><div><strong>${esc(user?.name||'')}</strong><span>${esc(user?.role||'')}</span></div><span>⌄</span></div></div></header><section class="content"><div id="accountStatusBanner"></div><div id="pageHead"></div><div id="status"></div><div id="content"></div><div class="footer-line"><span>© 2026 Pepiko, Inc.</span><span>platform.pepiko.ai · connected to platform-core-service</span></div></section></main></div><div id="modal" class="hidden"></div>`; $$('a.nav-link[data-page],a[data-route]').forEach(a=>a.onclick=e=>{e.preventDefault();showPage(a.dataset.page||a.dataset.route)}); renderAccountBanner(); if(!accountBlocked()){hydratePlaygroundProductNav(); if(productNavRefreshTimer)clearInterval(productNavRefreshTimer); productNavRefreshTimer=setInterval(()=>{if(token)hydratePlaygroundProductNav()},15000);}else if(productNavRefreshTimer){clearInterval(productNavRefreshTimer); productNavRefreshTimer=null;}}
function renderAccountBanner(){const el=$('#accountStatusBanner'); if(el)el.innerHTML=accountBlocked()?`<div class="portal-alert warning" style="display:flex">${esc(accountBlockedMessage())}</div>`:''}
async function hydratePlaygroundProductNav(products=null){const el=$('#playgroundProductNav'); if(!el)return; try{products=products||await api('/api/customer/products'); cache.products=products; el.innerHTML=products.map(p=>`<a class="nav-link product-link" style="min-height:30px;padding-left:38px;font-size:12px" href="${routeForPage('playground',p.product_code)}" data-page="playground" data-product="${esc(p.product_code)}"><span class="nav-icon">↳</span>${esc(p.name)}</a>`).join(''); $$('a.product-link[data-product]').forEach(a=>a.onclick=e=>{e.preventDefault();showProductPlayground(a.dataset.product)}); activate(currentPage);}catch{}}
function head(title, desc, actions=''){ $('#pageHead').innerHTML=`<div class="page-head"><div class="page-title"><div class="breadcrumb">pepiko.ai / ${esc(title)}</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="page-actions">${actions}</div></div>`}
function activate(id){currentPage=id; $$('.nav-link').forEach(b=>{const isProduct=b.dataset.product; b.classList.toggle('active', isProduct?b.dataset.product===selectedPlaygroundProductCode:b.dataset.page===id&&!selectedPlaygroundProductCode);});}
async function showPage(id,{replace=false,skipRoute=false,productCode=''}={}){selectedPlaygroundProductCode=id==='playground'?productCode:'';const route=routeForPage(id,selectedPlaygroundProductCode);if(skipRoute&&location.pathname!==route)history.replaceState({page:id,productCode:selectedPlaygroundProductCode},'',route);if(!skipRoute){if(replace)history.replaceState({page:id,productCode:selectedPlaygroundProductCode},'',route);else pushRoute(id,selectedPlaygroundProductCode)}activate(id); setStatus(''); renderAccountBanner(); renderPageLoading(); if(accountBlocked()){head('Account Suspended','Your customer account is not active. Portal actions and API access are disabled until the account is reactivated.','<button class="btn" onclick="logout()">Logout</button>'); $('#content').innerHTML=`<div class="panel"><h2>Account access disabled</h2><p class="muted">${esc(accountBlockedMessage())}</p><div style="margin-top:18px">${table(['Account','Status','Allowed action'],[[esc(user?.organization_name||'-'),badge(accountStatus()),'Contact Pepiko support or your account owner']])}</div></div>`; setStatus(accountBlockedMessage(),'warning'); return;} try{await ({dashboard,playground,apiKeys,usage,billing,reports,projects,team,webhooks,audit,support}[id]||dashboard)()}catch(e){setStatus(e.message,true)}}
function showProductPlayground(productCode){showPage('playground',{productCode})}
function renderApp(){shell(); currentPage=pageFromPath(); const productCode=currentPage==='playground'?productFromPath():''; showPage(currentPage,{replace:true,skipRoute:location.pathname===routeForPage(currentPage,productCode),productCode})}
window.addEventListener('popstate',()=>{if(token){const page=pageFromPath();showPage(page,{skipRoute:true,productCode:page==='playground'?productFromPath():''})}});
window.addEventListener('focus',()=>{if(token)hydratePlaygroundProductNav()});
